language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"

before_install:
  - npm i -g typescript typings

notifications:
	webhooks:
		urls:
			- https://webhooks.gitter.im/e/5934cdd7f561ce7a96d2
		on_success: change  # options: [always|never|change] default: always
		on_failure: always  # options: [always|never|change] default: always
		on_start: never     # options: [always|never|change] default: always