# kick: 1

version: 2.1

commands:
  run_tests:
    description: "Build Alterior and run the test suite"
    parameters:
      version:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-<< parameters.version >>-{{ checksum "package.json" }}
          - v1-dependencies-<< parameters.version >>-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-<< parameters.version >>-{{ checksum "package.json" }}
      - run: npm test
jobs:
  node-19:
    docker:
      - image: cimg/node:19.4
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "19"
  node-18:
    docker:
      - image: cimg/node:18.13
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "18"
  node-16:
    docker:
      - image: cimg/node:16.19
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "16"
  node-14:
    docker:
      - image: cimg/node:14.21
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "14"

workflows:
  version: 2
  build:
    jobs:
      - node-19
      - node-18
      - node-16
      - node-14
