# kick: 1

version: 2.1

commands:
  run_tests:
    description: "Build Alterior and run the test suite"
    parameters:
      version:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-<< parameters.version >>-{{ checksum "package.json" }}
          - v1-dependencies-<< parameters.version >>-
      - run: npm install
      - run: ./node_modules/.bin/lerna bootstrap --concurrency=2
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-<< parameters.version >>-{{ checksum "package.json" }}
      - run: npm test
jobs:
  node-14:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "14"
  node-12:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "12"
  node-11:
    docker:
      - image: circleci/node:11
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "11"
  node-10:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "10"

workflows:
  version: 2
  build:
    jobs:
      - node-14
      - node-12
      - node-11
      - node-10
